# Ajustes de Gradle para todo el proyecto.
# Los ajustes hechos desde el IDE (Android Studio) sobreescriben este archivo.

org.gradle.jvmargs=-Xmx4096m -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configureondemand=false

kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2048m

# AndroidX y recursos
android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=false
android.nonFinalResIds=false

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
